spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dokcer
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.
        #show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: true